Module 14 Activity: Continuous Deployment Steps
neu-se/CS4530-Fall-2024 pull request #39
Opened 2024-10-02 16:38 UTC by anikeshk

2024-10-06 21:18 UTC, ViharReddy requested changes

2024-10-06 21:18 UTC, ViharReddy commented on Activities/Module14 Activity.md
> +   8. In the Environment Variables section, add a variable called `REACT_APP_API_URL`. For the value, add the server URL.
change to "REACT_APP_SERVER_URL"

2024-10-07 17:30 UTC, anikeshk commented on Activities/Module14 Activity.md
> +   8. In the Environment Variables section, add a variable called `REACT_APP_API_URL`. For the value, add the server URL.
I have updated the env variable name.

2024-10-15 10:04 UTC, anikeshk commented
Added the following changes:
1. Minor grammatical mistakes.
2. Specified what default collections the student will see after they connect the deployed MongoDB cluster to their MongoDB Compass.
3. Added `fake_so` to end of the connection string.
4. Re-rephrased the environmental instructions to use the `.env` file.

2024-10-20 02:18 UTC, closed without merging

2024-10-20 02:19 UTC, abhutta0 commented
Closed without merge. Will work on #52 instead!