Added Heroku deployment instructions
neu-se/CS4530-Fall-2024 pull request #61
Opened 2024-11-07 06:19 UTC by PavanKumar06

2024-11-11 03:36 UTC, anikeshk requested changes

2024-11-11 03:36 UTC, anikeshk commented on tutorials/heroku-deployment.md
> +2. **Configure Required Files**
By now, most if not all teams would have added new dependencies in their `package.json`. From what I can see in the `package.json` in the assets folder is that the "start" script has been changed. So we should just ask the students to make a change in their existing `package.json`, as follows.

- Move "dotenv" from the "devDependecies" to "dependencies".
- Change the "start" script in your `server/package.json` from "ts-node server.ts" to "node dist/server.js".
- Add a new script called "start:dev" with the value "ts-node server.ts". You can use this for your local development.

Your `package.json` should look something like this:

```
{
  "dependencies": {
    ...original dependencies and any dependencies you have added
    "dotenv": "^16.4.5"
  },
  "devDependencies": {
    ...
  },
  "scripts": {
    "start": "node ./dist/server.js",
    "start:dev": "ts-node server.ts",
    "lint": "eslint .",
    "lint:fix": "eslint . --fix",
    "test": "jest -w=1 --coverage --detectOpenHandles",
    "build": "tsc",
    "start:prod": "node ./dist/server.js",
    "stryker": "stryker run"
  }
}
```

Similarly, I see only one change in the `tsconfig.json`, as follows.

- Go to `server/tsconfig.json` and scroll to the end. Modify the "include" and "exclude" values to the following:

```
"include": ["./**/*.ts"],
 "exclude": ["node_modules", "dist"]
```

If there are other similar changes we can add it as instructions. This way the students retain their existing file and dependencies.

2024-11-11 03:36 UTC, anikeshk commented on tutorials/heroku-deployment.md
> +     Value: mongodb+srv://dspavankumar99:<password>@assignment.wmfzac9.mongodb.net
Change the value from `mongodb+srv://dspavankumar99:<password>@assignment.wmfzac9.mongodb.net` to `<your MongoDB connection string>`

2024-11-11 03:36 UTC, anikeshk commented on tutorials/heroku-deployment.md
> +     npx ts-node populate_db.ts mongodb+srv://dspavankumar99:<password>@assignment.wmfzac9.mongodb.net/fake_so
In the [MongoDB Atlas instructions](https://neu-se.github.io/CS4530-Fall-2024/activities/continuous-deployment#setup-your-mongodb-database) we have asked the students to run the `populate_db.ts` script already, so don't need to ask them to read it again - switching from Render to Heroku won't impact the MongoDB Atlas deployment.
Please remove this step.

2024-11-11 03:36 UTC, anikeshk commented on tutorials/heroku-deployment.md
> +3. **Verify Database Connection**
We should have a `## Step 6: Update client env variables on Render.com` to inform students to update the server URL from the Render.com URL to the Heroku URL. These steps can be something along these lines:

1. Open the [Render Dashboard](https://dashboard.render.com/).
2. Choose the project you have created, and go back to service with type "Static Site" (your client deployment).
3. Click on the “Environment” tab.
4. Change the value of the `REACT_APP_SERVER_URL` env to the Heroku URL (you can find this in your Heroku app's "Settings" page, under the "Domains" section).
5. After the client finishes re-deploying, check if the client is sending queries to the new Heroku server deployment successfully.
6. (Optional) If the new Heroku server deployment is working correctly, delete the server deployment from Render.

2024-11-11 03:36 UTC, anikeshk commented on tutorials/heroku-deployment.md
> +# Steps to Set Up Heroku Deployment for Your Backend Service
PR is created to [neu-se:all_tutorials](https://github.com/neu-se/CS4530-Fall-2024/tree/all_tutorials) but I think PRs should be created to [neu-se:main](https://github.com/neu-se/CS4530-Fall-2024/tree/main) for the Netlify auto-deployment to work.

2024-11-13 18:19 UTC, PavanKumar06 commented on tutorials/heroku-deployment.md
> +     Value: mongodb+srv://dspavankumar99:<password>@assignment.wmfzac9.mongodb.net
Done

2024-11-13 21:27 UTC, anikeshk commented
Two more things to add:

1. <add as a note under wherever you tell the students to create a new repo for sever>

Once you separate the repository into one with client and one with the server, update the `.github\workflows\main.yml` in each as the following:

`server`

```
name: FakeStackOverflow CI
on: # Controls when the action will run.
  # Triggers the workflow on push or pull request events but only for the master branch. If you want to trigger the action on other branches, add here
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test: #
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Launch MongoDB Server
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: "7.0"

      - name: Build and lint frontend
        if: ${{ always() }}
        env:
          REACT_APP_SERVER_URL: http://localhost:8000
        run: cd client; npm ci && npm run build && npm run lint

```

`client`

```
name: FakeStackOverflow CI
on: # Controls when the action will run.
  # Triggers the workflow on push or pull request events but only for the master branch. If you want to trigger the action on other branches, add here
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test: #
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Launch MongoDB Server
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: "7.0"

      - name: Build backend service
        if: ${{ always() }}
        run: cd server; npm ci

      - name: Test backend server
        if: ${{ always() }}
        env:
          # Pass the environmental variables for the backend tests to use
          MONGODB_URI: mongodb://localhost:27017
        run: |
          cd server

          npm run start & sleep 10

          echo "Checking if the server is running..."
          curl --fail 'http://localhost:8000/question/getQuestion?order=newest&search=' || (echo "Server failed to start" && killall node && exit 1)

          echo "Server started successfully. Now stopping..."
          killall node

          npm run test

      - name: Lint backend
        if: ${{ always() }}
        run: cd server; npm run lint

```

2. <add as a note in the end>

  - In case you are still running into memory issues in the Heroku deployment, you can update the "Dynos" type.
  - Add the steps from here: https://help.heroku.com/XX3MKY2E/how-do-i-change-the-dyno-types-for-my-application

2024-11-14 01:38 UTC, PavanKumar06 commented on tutorials/heroku-deployment.md
> +     npx ts-node populate_db.ts mongodb+srv://dspavankumar99:<password>@assignment.wmfzac9.mongodb.net/fake_so
Done

2024-11-14 03:49 UTC, PavanKumar06 commented on tutorials/heroku-deployment.md
> +2. **Configure Required Files**
Done

2024-11-14 03:54 UTC, PavanKumar06 commented on tutorials/heroku-deployment.md
> +3. **Verify Database Connection**
Done

2024-11-14 06:32 UTC, PavanKumar06 commented
I have resolved the comments made by Anikesh. If everything works fine I will close this PR and raise a new PR for Module13 Activity.md file

2024-11-14 16:02 UTC, VatsalMehta27 commented on tutorials/heroku-deployment.md
> +   # Server - GitHub Actions CI Workflow Configuration
This is for client

2024-11-14 16:02 UTC, VatsalMehta27 commented on tutorials/heroku-deployment.md
> +            - name: Launch MongoDB Server
Not needed in client

2024-11-14 16:02 UTC, VatsalMehta27 commented on tutorials/heroku-deployment.md
> +   # Client - GitHub Actions CI Workflow Configuration
Should be server

2024-11-15 04:25 UTC, closed without merging